version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 0000
      POSTGRES_USER: postgres
      POSTGRES_DB: t_users
app:
  image: m_securite
  port:
    -1300:3000