apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: nahladhouibi/micro_securite
        ports:
        - containerPort: 6000
        env:
        - name: PORT
          value: "6000"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_NAME
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PORT
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: JWT_SECRET
        - name: JWT_REFRESH_EXPIRATION
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: JWT_REFRESH_EXPIRATION
