apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_USER: cG9zdGdyZXM=  # base64 encoded 'postgres'
  DB_PASSWORD: MDAwMA==  # base64 encoded '0000'
  DB_NAME: dF91c2Vycw==  # base64 encoded 't_users'
  DB_PORT: NTQzMg==      # base64 encoded '5432'

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  JWT_SECRET: QUNDQzAwOSowOQ==  # base64 encoded 'ACCC009*09'
  JWT_REFRESH_EXPIRATION: MQ==  # base64 encoded '1'
